#pragma once

#include <string>
#include <unordered_map>

std::unordered_map<std::string, std::string> weather_description = {
    { "clearsky_day", "Clear sky (day)" },
    { "clearsky_night", "Clear sky (night)"},
    {"clearsky_polartwilight", "Clear sky (polar twilight)"},
    {   "fair_day", "Fair (day)"},
    {   "fair_night", "Fair (night)" },
    {   "fair_polartwilight", "Fair (polar twilight)" },
    { "partlycloudy_day", "Partly cloudy (day)" },
    { "partlycloudy_night", "Partly cloudy (night)" },
    { "partlycloudy_polartwilight", "Partly cloudy (polar twilight)" },
    { "cloudy", "Cloudy"},
    { "rainshowers_day", "Rain showers (day)" },
    { "rainshowers_night", "Rain showers (night)" },
    {"rainshowers_polartwilight", "Rain showers (polar twilight)" },
    { "rainshowersandthunder_day", "Rain showers and thunder (day)" },
    { "rainshowersandthunder_night", "Rain showers and thunder (night)" },
    { "rainshowersandthunder_polartwilight", "Rain showers and thunder (polar twilight)" },
    { "sleetshowers_day", "Sleet showers (day)" },
    { "sleetshowers_night", "Sleet showers (night)" },
    { "sleetshowers_polartwilight", "Sleet showers (polar twilight)" },
    { "snowshowers_day", "Snow showers (day)" },
    { "snowshowers_night", "Snow showers (night)" },
    { "snowshowers_polartwilight", "Snow showers (polar twilight)" },
    { "rain", "Rain"},
    { "heavyrain", "Heavy rain"},
    { "heavyrainandthunder", "Heavy rain and thunder"},
    { "sleet", "Sleet"},
    { "snow", "Snow"},
    { "snowandthunder", "Snow and thunder"},
    { "fog", "Fog"},
    { "sleetshowersandthunder_day", "Sleet showers and thunder (day)" },
    { "sleetshowersandthunder_night", "Sleet showers and thunder (night)" },
    { "sleetshowersandthunder_polartwilight", "Sleet showers and thunder (polar twilight)" },
    { "snowshowersandthunder_day", "Snow showers and thunder (day)" },
    { "snowshowersandthunder_night", "Snow showers and thunder (night)" },
    { "snowshowersandthunder_polartwilight", "Snow showers and thunder (polar twilight)" },
    { "rainandthunder", "Rain and thunder"},
    { "sleetandthunder", "Sleet and thunder"},
    { "lightrainshowersandthunder_day", "Light rain showers and thunder (day)" },
    { "lightrainshowersandthunder_night", "Light rain showers and thunder (night)" },
    { "lightrainshowersandthunder_polartwilight", "Light rain showers and thunder (polar twilight)" },
    { "heavyrainshowersandthunder_day", "Heavy rain showers and thunder (day)" },
    { "heavyrainshowersandthunder_night", "Heavy rain showers and thunder (night)" },
    { "heavyrainshowersandthunder_polartwilight", "Heavy rain showers and thunder (polar twilight)" },
    { "lightssleetshowersandthunder_day", "Light sleet showers and thunder (day)" },
    { "lightssleetshowersandthunder_night", "Light sleet showers and thunder (night)" },
    { "lightssleetshowersandthunder_polartwilight", "Light sleet showers and thunder (polar twilight)" },
    { "heavysleetshowersandthunder_day", "Heavy sleet showers and thunder (day)" },
    { "heavysleetshowersandthunder_night", "Heavy sleet showers and thunder (night)" },
    { "heavysleetshowersandthunder_polartwilight", "Heavy sleet showers and thunder (polar twilight)" },
    { "lightssnowshowersandthunder_day", "Light snow showers and thunder (day)" },
    { "lightssnowshowersandthunder_night", "Light snow showers and thunder (night)" },
    { "lightssnowshowersandthunder_polartwilight", "Light snow showers and thunder (polar twilight)" },
    { "heavysnowshowersandthunder_day", "Heavy snow showers and thunder (day)" },
    { "heavysnowshowersandthunder_night", "Heavy snow showers and thunder (night)" },
    { "heavysnowshowersandthunder_polartwilight", "Heavy snow showers and thunder (polar twilight)" },
    { "lightrainandthunder", "Light rain and thunder"},
    { "lightsleetandthunder", "Light sleet and thunder"},
    { "heavysleetandthunder", "Heavy sleet and thunder"},
    { "lightsnowandthunder", "Light snow and thunder"},
    { "heavysnowandthunder", "Heavy snow and thunder"},
    { "lightrainshowers_day", "Light rain showers (day)" },
    { "lightrainshowers_night", "Light rain showers (night)" },
    { "lightrainshowers_polartwilight", "Light rain showers (polar twilight)" },
    { "heavyrainshowers_day", "Heavy rain showers (day)" },
    { "heavyrainshowers_night", "Heavy rain showers (night)" },
    { "heavyrainshowers_polartwilight", "Heavy rain showers (polar twilight)" },
    { "lightsleetshowers_day", "Light sleet showers (day)" },
    { "lightsleetshowers_night", "Light sleet showers (night)" },
    { "lightsleetshowers_polartwilight", "Light sleet showers (polar twilight)" },
    { "heavysleetshowers_day", "Heavy sleet showers (day)" },
    { "heavysleetshowers_night", "Heavy sleet showers (night)" },
    { "heavysleetshowers_polartwilight", "Heavy sleet showers (polar twilight)" },
    { "lightsnowshowers_day", "Light snow showers (day)" },
    { "lightsnowshowers_night", "Light snow showers (night)" },
    { "lightsnowshowers_polartwilight", "Light snow showers (polar twilight)" },
    { "heavysnowshowers_day", "Heavy snow showers (day)" },
    { "heavysnowshowers_night", "Heavy snow showers (night)" },
    { "heavysnowshowers_polartwilight", "Heavy snow showers (polar twilight)" },
    { "lightrain", "Light rain"},
    { "lightsleet", "Light sleet"},
    { "heavysleet", "Heavy sleet"},
    { "lightsnow", "Light snow"},
    { "heavysnow", "Heavy snow"}
};

